name: E2e test
description: Run e2e tests

inputs:
  e2e-base-url:
    description: Base url
    required: true

runs:
  using: 'composite'
  steps:
    - name: Show URL1
      run: |
        echo "BASE_URL: ${{ inputs.e2e-base-url }}"
      shell: bash

    - name: Show URL
      uses: actions/github-script@v7
      with:
        script: |
          const { DEPLOY_URL } = process.env
          console.log(DEPLOY_URL);
    - name: Run tests
      run: npm run test:e2e
      shell: bash
      env:
        E2E_BASE_URL: ${{ inputs.e2e-base-url }}

