name: E2e test
description: Run e2e tests

inputs:
  e2e-base-url:
    description: Base url
    required: true
  bypass-secret:
    description: Bypass secret
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run tests
      run: npm run test:e2e
      shell: bash
      env:
        E2E_BASE_URL: ${{ inputs.e2e-base-url }}
        VERCEL_AUTOMATION_BYPASS_SECRET: ${{ inputs.bypass-secret }}

