name: Deploy Netlify

on:
  workflow_call:


jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Run lint and tests
        uses: ./.github/actions/lint-and-test

      - name: Build app
        run: npm run build
        env:
          VITE_ENVIRONMENT: 'Development'
          VITE_AWS_MONITORING_API: ${{ secrets.AWS_MONITORING_API }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          github-deployment-environment: "Development"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
